import { useEffect } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, BarChart3, Check, ClipboardCheck, FolderKanban, ListChecks, PlayCircle } from 'lucide-react'
import { useAuth } from '../context/AuthContext'

const features = [
  [FolderKanban, 'Suites', 'Group related test cases by feature or module, so coverage stays organized as your product grows.'],
  [ListChecks, 'Test Cases', 'Write structured cases with steps, preconditions, priority, and automation tags.'],
  [PlayCircle, 'Test Runs', 'Execute a batch of cases and mark pass, fail, blocked, or skipped in real time.'],
  [BarChart3, 'Analytics', 'Track pass-rate trends, suite health, and flaky tests before they erode trust.'],
]

const steps = [
  ['01', 'Create your suites', 'Set up folders for each feature or module you need to cover.'],
  ['02', 'Write test cases', 'Add steps, preconditions, and priority for every scenario that matters.'],
  ['03', 'Run & analyze', 'Execute runs, record results, and watch pass-rate trends over time.'],
]

function ResultRow({ code, title, status, tone, delay }) {
  return <div className="mock-row flex items-center justify-between border-b border-line px-3 py-2.5 last:border-0" style={{ animationDelay: delay }}><span className="flex min-w-0 items-center gap-2 text-xs"><span className="font-mono text-[10px] text-ink-muted">{code}</span><span className="truncate font-medium text-ink">{title}</span></span><span className={`ml-3 rounded px-2 py-0.5 text-[10px] font-semibold ${tone}`}>{status}</span></div>
}

export default function Home() {
  const { user } = useAuth()
  const workspacePath = user ? '/dashboard' : '/login'

  useEffect(() => {
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => {
      if (entry.isIntersecting) { entry.target.classList.add('in-view'); observer.unobserve(entry.target) }
    }), { threshold: 0.15 })
    const elements = document.querySelectorAll('[data-home-animate]')
    elements.forEach((element) => observer.observe(element))
    return () => observer.disconnect()
  }, [])

  return <div id="top" className="min-h-screen bg-paper text-ink">
    <header className="fixed inset-x-0 top-0 z-50"><div className="mx-auto max-w-6xl px-5 sm:px-6"><div className="nav-shadow flex items-center justify-between rounded-b-lg bg-paper/90 px-2 py-3 backdrop-blur-md sm:py-4">
      <Link to="/" className="flex items-center gap-2.5"><span className="flex h-8 w-8 items-center justify-center rounded bg-ink"><ClipboardCheck size={17} className="text-white" /></span><span className="text-[15px] font-bold tracking-tight">QAlibrate</span></Link>
      <nav className="hidden items-center gap-8 text-sm font-medium text-ink-muted md:flex"><a href="#features" className="hover:text-ink">Features</a><a href="#how-it-works" className="hover:text-ink">How it works</a><Link to="/about" className="hover:text-ink">About</Link></nav>
            <div className="flex items-center gap-1 sm:gap-3">
              {user && <Link to="/profile" className="max-w-full break-words px-2 py-2 text-sm font-semibold text-ink-soft hover:text-signal sm:px-3">{user.full_name}</Link>}
              <Link to={workspacePath} className="px-2 py-2 text-sm font-semibold text-ink-soft hover:text-signal sm:px-3">{user ? 'Workspace' : 'Sign in'}</Link>
              {!user && <Link to="/register" className="btn-primary px-3 py-2.5 text-sm">Get started <ArrowRight size={15} /></Link>}
            </div>
    </div></div></header>

    <main>
      <section className="relative overflow-hidden pb-24 pt-36 md:pb-32 md:pt-48"><div className="pointer-events-none absolute -top-24 left-1/2 h-[420px] w-[720px] -translate-x-1/2 rounded-full bg-signal/5 blur-3xl" /><div className="relative mx-auto grid max-w-6xl items-center gap-14 px-5 sm:px-6 lg:grid-cols-2">
        <div><div data-home-animate className="home-reveal inline-flex items-center gap-2 rounded-full border border-line bg-white px-3.5 py-1.5 text-xs font-semibold text-ink-soft"><span className="pulse-dot h-1.5 w-1.5 rounded-full bg-pass" /> Built for QA teams, not spreadsheets</div><h1 data-home-animate className="home-reveal stagger-1 mt-6 text-4xl font-extrabold leading-[1.08] tracking-tight md:text-[3.25rem]">Ship with confidence.<br /><span className="grad-underline inline-block pb-1">Test with clarity.</span></h1><p data-home-animate className="home-reveal stagger-2 mt-6 max-w-md text-[17px] leading-relaxed text-ink-muted">QAlibrate keeps your suites, test cases, and execution history in one clean workspace, built to give QA teams signal, not noise.</p><div data-home-animate className="home-reveal stagger-3 mt-9 flex flex-wrap gap-3"><Link to={user ? '/dashboard' : '/register'} className="btn-primary">{user ? 'Open workspace' : 'Create free account'} <ArrowRight size={16} /></Link>{!user && <Link to="/login" className="btn-secondary">Sign in</Link>}</div><div data-home-animate className="home-reveal stagger-4 mt-10 flex flex-wrap gap-x-6 gap-y-3 text-xs font-medium text-ink-muted"><span className="flex items-center gap-1.5"><Check size={14} className="text-pass" /> No credit card</span><span className="flex items-center gap-1.5"><Check size={14} className="text-pass" /> Self-hosted &amp; open</span><span className="flex items-center gap-1.5"><Check size={14} className="text-pass" /> Set up in minutes</span></div></div>
        <div data-home-animate className="home-reveal stagger-2 relative"><div className="float-slow rounded-lg border border-line bg-white p-5 shadow-[0_20px_60px_-15px_rgba(18,21,28,0.18)]"><div className="mb-4 flex items-center justify-between"><div className="flex gap-2"><span className="h-2.5 w-2.5 rounded-full bg-fail/70" /><span className="h-2.5 w-2.5 rounded-full bg-blocked/70" /><span className="h-2.5 w-2.5 rounded-full bg-pass/70" /></div><span className="text-[11px] font-semibold uppercase tracking-wide text-ink-muted">Sprint 24 Regression</span></div><div className="mb-4 grid grid-cols-3 gap-3"><div className="rounded border border-line px-3 py-2.5"><p className="text-[10px] font-semibold uppercase text-ink-muted">Test Cases</p><p className="mt-1 text-xl font-bold">128</p></div><div className="rounded border border-line px-3 py-2.5"><p className="text-[10px] font-semibold uppercase text-ink-muted">Pass Rate</p><p className="mt-1 text-xl font-bold text-pass">94%</p></div><div className="rounded border border-line px-3 py-2.5"><p className="text-[10px] font-semibold uppercase text-ink-muted">Flaky</p><p className="mt-1 text-xl font-bold text-blocked">3</p></div></div><div className="overflow-hidden rounded border border-line"><ResultRow code="TC-0041" title="Login with valid credentials" status="Passed" tone="bg-pass-soft text-pass" delay="0.1s" /><ResultRow code="TC-0042" title="Promo code applies discount" status="Failed" tone="bg-fail-soft text-fail" delay="0.25s" /><ResultRow code="TC-0043" title="Session expires on timeout" status="Blocked" tone="bg-blocked-soft text-blocked" delay="0.4s" /></div></div><div className="float-slow-delay absolute -bottom-6 -left-6 hidden rounded-lg border border-line bg-white px-4 py-3 shadow-lg sm:block"><p className="text-[10px] font-semibold uppercase text-ink-muted">Suite health</p><div className="mt-1.5 flex items-end gap-1"><span className="h-4 w-2 rounded-sm bg-signal/30" /><span className="h-6 w-2 rounded-sm bg-signal/50" /><span className="h-8 w-2 rounded-sm bg-signal/70" /><span className="h-5 w-2 rounded-sm bg-signal/50" /><span className="h-9 w-2 rounded-sm bg-signal" /></div></div></div>
      </div></section>

      <section className="border-y border-line bg-white"><div className="mx-auto max-w-6xl px-5 py-6 sm:px-6"><p data-home-animate className="home-reveal text-center text-xs font-semibold uppercase tracking-wide text-ink-muted">The lightweight alternative to TestRail and Zephyr</p></div></section>

      <section id="features" className="py-24 md:py-32"><div className="mx-auto max-w-6xl px-5 sm:px-6"><div className="max-w-xl"><p data-home-animate className="home-reveal text-xs font-semibold uppercase text-signal">What you get</p><h2 data-home-animate className="home-reveal stagger-1 mt-3 text-3xl font-extrabold tracking-tight md:text-4xl">Everything a QA workflow actually needs</h2><p data-home-animate className="home-reveal stagger-2 mt-4 leading-relaxed text-ink-muted">No bloated feature set to wade through, just the parts of test management QA teams touch every day.</p></div><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{features.map(([Icon, title, text], index) => <div key={title} data-home-animate className={`home-reveal stagger-${index + 1} feature-card rounded-lg border border-line bg-white p-6`}><div className="mb-5 flex h-10 w-10 items-center justify-center rounded bg-signal-soft text-signal"><Icon size={19} /></div><h3 className="text-[15px] font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-ink-muted">{text}</p></div>)}</div></div></section>

      <section id="how-it-works" className="border-y border-line bg-white py-24 md:py-32"><div className="mx-auto max-w-6xl px-5 sm:px-6"><div className="mx-auto max-w-xl text-center"><p data-home-animate className="home-reveal text-xs font-semibold uppercase text-signal">The workflow</p><h2 data-home-animate className="home-reveal stagger-1 mt-3 text-3xl font-extrabold tracking-tight md:text-4xl">From blank suite to trusted release</h2></div><div className="relative mt-16 grid gap-10 md:grid-cols-3"><div className="absolute left-[16.6%] right-[16.6%] top-6 hidden h-px bg-line md:block" />{steps.map(([number, title, text], index) => <div key={number} data-home-animate className={`home-reveal stagger-${index + 1} relative text-center`}><div className="relative z-10 mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-ink text-sm font-bold text-white">{number}</div><h3 className="mt-5 text-[15px] font-bold">{title}</h3><p className="mt-2 px-4 text-sm leading-relaxed text-ink-muted">{text}</p></div>)}</div></div></section>

      <section id="about" className="py-24 md:py-32"><div className="mx-auto grid max-w-6xl items-start gap-14 px-5 sm:px-6 lg:grid-cols-5"><div className="lg:col-span-2"><p data-home-animate className="home-reveal text-xs font-semibold uppercase text-signal">About QAlibrate</p><h2 data-home-animate className="home-reveal stagger-1 mt-3 text-3xl font-extrabold tracking-tight">Built by testers, for testers</h2></div><div className="space-y-5 text-[15px] leading-relaxed text-ink-soft lg:col-span-3"><p data-home-animate className="home-reveal stagger-1">QAlibrate started from a simple frustration: most test case tools are either too heavyweight for a small team, or too limited to replace a spreadsheet.</p><p data-home-animate className="home-reveal stagger-2">The name is a play on “QA” and “calibrate”, the idea that good testing is about recalibrating your confidence in the product as it changes.</p><div data-home-animate className="home-reveal stagger-3 flex flex-wrap gap-8 pt-2"><div><p className="text-2xl font-extrabold">100%</p><p className="mt-1 text-xs text-ink-muted">Self-hosted &amp; yours</p></div><div><p className="text-2xl font-extrabold">4</p><p className="mt-1 text-xs text-ink-muted">Core workflows</p></div><div><p className="text-2xl font-extrabold">&lt; 5 min</p><p className="mt-1 text-xs text-ink-muted">To your first run</p></div></div><Link to="/about" className="inline-flex items-center gap-2 pt-2 text-sm font-bold text-signal hover:text-ink">Read our story <ArrowRight size={15} /></Link></div></div></section>

      <section className="pb-24 md:pb-32"><div className="mx-auto max-w-6xl px-5 sm:px-6"><div data-home-animate className="home-reveal relative overflow-hidden rounded-xl bg-ink px-8 py-14 text-center md:px-16 md:py-16"><div className="pointer-events-none absolute -right-16 -top-16 h-56 w-56 rounded-full bg-signal/20 blur-3xl" /><h2 className="relative text-2xl font-extrabold text-white md:text-3xl">Ready to bring order to your test suite?</h2><p className="relative mx-auto mt-3 max-w-md text-white/60">Create your workspace and run your first test case in minutes.</p><div className="relative mt-8 flex flex-wrap justify-center gap-3"><Link to={user ? '/dashboard' : '/register'} className="inline-flex items-center gap-2 rounded bg-white px-6 py-3 text-sm font-bold text-ink hover:bg-signal hover:text-white">{user ? 'Open workspace' : 'Create free account'} <ArrowRight size={16} /></Link>{!user && <Link to="/login" className="inline-flex items-center gap-2 rounded border border-white/20 px-6 py-3 text-sm font-bold text-white hover:bg-white/10">Sign in</Link>}</div></div></div></section>
    </main>

    <footer className="border-t border-line bg-white"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-6 px-5 py-10 sm:flex-row sm:px-6"><Link to="/" className="flex items-center gap-2.5"><span className="flex h-7 w-7 items-center justify-center rounded bg-ink"><ClipboardCheck size={14} className="text-white" /></span><span className="text-sm font-bold">QAlibrate</span></Link><nav className="flex items-center gap-6 text-sm font-medium text-ink-muted"><a href="#features" className="hover:text-ink">Features</a><a href="#how-it-works" className="hover:text-ink">How it works</a><Link to="/about" className="hover:text-ink">About</Link><Link to={workspacePath} className="hover:text-ink">{user ? 'Workspace' : 'Sign in'}</Link></nav><p className="text-xs text-ink-muted">© 2026 QAlibrate. Built for QA teams.</p></div></footer>
  </div>
}
